In [1]:
import understatapi
from understatapi import UnderstatClient
import pandas as pd
import matplotlib
from matplotlib import pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [2]:
# 1. Open the connection
with UnderstatClient() as understat:
    # Understat uses the start year (2025) for the 2025/26 season
    # We get player data for the whole league first
    league_data = understat.league(league="La_Liga").get_player_data(season="2025")

# 2. Convert to DataFrame
df = pd.DataFrame(league_data)

# 3. Filter for only Real Madrid players
# (Understat usually uses "Real Madrid" as the team_title)
real_madrid_df = df[df['team_title'] == 'Real Madrid'].copy()

# 4. Clean the data (Convert strings to numbers)
cols_to_fix = ['goals', 'assists', 'xG', 'xA', 'shots', 'key_passes']
for col in cols_to_fix:
    real_madrid_df[col] = pd.to_numeric(real_madrid_df[col])

# 5. Display the top 5 scorers for Real Madrid this season
top_madrid_scorers = real_madrid_df.sort_values(by='goals', ascending=False).head(10)

print("--- Real Madrid Top 5 Scorers (2025/26) ---")
df_top_10 = pd.DataFrame(top_madrid_scorers[['player_name', 'goals', 'xG', 'assists', 'xA']])


# Make Rank a column
df_top_10 = df_top_10.reset_index(drop=True)
df_top_10 = df_top_10.reset_index()

df_top_10 = df_top_10.rename(columns={'index': 'Rank'})

df_top_10['Rank'] = df_top_10.index + 1

# Set the index to be invisible empty text
df_top_10

--- Real Madrid Top 5 Scorers (2025/26) ---

   Rank           player_name  goals         xG  assists        xA
0     1  Kylian Mbappe-Lottin     23  21.647808        4  6.512942
1     2       Vinícius Júnior      9   9.973474        5  5.246589
2     3       Jude Bellingham      4   6.213100        3  2.522140
3     4        Gonzalo García      4   3.992838        0  0.905134
4     5            Arda Güler      3   4.583801        8  7.376322
5     6     Federico Valverde      2   1.230292        7  4.435267
6     7      Álvaro Fernández      2   0.401170        2  1.424036
7     8                  Raúl      2   1.406357        0  0.208544
8     9   Aurelien Tchouameni      1   2.365042        0  2.157384
9    10     Eduardo Camavinga      1   1.045046        0  1.213536

In [3]:
df_top_10

   Rank           player_name  goals         xG  assists        xA
0     1  Kylian Mbappe-Lottin     23  21.647808        4  6.512942
1     2       Vinícius Júnior      9   9.973474        5  5.246589
2     3       Jude Bellingham      4   6.213100        3  2.522140
3     4        Gonzalo García      4   3.992838        0  0.905134
4     5            Arda Güler      3   4.583801        8  7.376322
5     6     Federico Valverde      2   1.230292        7  4.435267
6     7      Álvaro Fernández      2   0.401170        2  1.424036
7     8                  Raúl      2   1.406357        0  0.208544
8     9   Aurelien Tchouameni      1   2.365042        0  2.157384
9    10     Eduardo Camavinga      1   1.045046        0  1.213536

In [4]:
import understatapi